title: "UCSB CS56 pconrad"
github_url: https://github.com/UCSB-CS56-pconrad/UCSB-CS56-pconrad.github.io
mentor_url: https://ucsb-cs56-pconrad-mentors.github.io
github_repo: UCSB-CS56-pconrad.github.io
gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=19139
piazza_course_page: https://piazza.com/class/j80k1o0zsxg1j7

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048/
hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 
office_hours_page: https://ucsb-cs56-f16.github.io/info/office_hours/

legacy_wiki_url: https://foo.cs.ucsb.edu/56wiki
legacy_wiki_name: "56wiki"

curr_qtr: "W18"
curr_qtr_web_url: "https://ucsb-cs56-w18.github.io"
course: "CS56"
curr_qtr_github_org_url: "https://github.com/ucsb-cs56-w18"
curr_qtr_github_org: ucsb-cs56-w18

#kramdown:
#  parse_block_html: true

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/
    
  tutorials:
    output: true
    permalink: /tutorials/:path/


  textbooks:
    output: true
    permalink: /textbooks/:path/

  hfj:
    output: true
    permalink: /hfj/:path/

  hfdp:
    output: true
    permalink: /hfdp/:path/
    
  resources:
    output: true
    permalink: /resources/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: topic
      
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial
      
  - scope:
      path: ""
      type: hfj
    values:
      layout: chapter

  - scope:
      path: ""
      type: hfdp
    values:
      layout: chapter
      
  - scope:
      path: ""
      type: resources
    values:
      layout: topic
